.github/workflows/go-test.yaml

/cc @chizhg 
Part of: https://github.com/knative/test-infra/issues/2985
- Reworking the simpler github actions to allow prow to mark it as required.
- The github treates each matrix permutation as a unique status so when we move to go 1.18 the status that we are tracking for 1.17 
will now be different. Current test status is `"Build (1.17.x, ubuntu-latest)"`
- Once this is merged, can a repo admin run add the new test briefly and run `gh api 
repos/knative/serving/branches/main/protection/required_status_checks/contexts`
/kind enhancement

Change Build Test from Matrix

---

.github/workflows/releasability.yaml

We currently don't want to embed the version number here. This will break releasability jobs for release branches - since those numbers need to be hardcoded.
Instead we are embedding the defaults into the workflow template here: https://github.com/knative-sandbox/knobots/pull/170
Those templates are propagated to all the other repositories thus embedding the version numbers like before.
Note: this is a stop-gap until the release process or this action is re-done.

drop version numbers in releasability flow

---

.github/workflows/go-build.yaml
.github/workflows/go-test.yaml
.github/workflows/releasability.yaml
.github/workflows/release-notes.yaml
.github/workflows/style.yaml
.github/workflows/verify-codegen.yaml

Prow is already using go1.18 by default

bump go version to 1.18

---

.github/workflows/style.yaml

golangci lint action does not work currently wih go1.19, adjust go version to 1.18 for it to work
More context here: https://github.com/golangci/golangci-lint-action/issues/532

Bug in style action

---

.github/workflows/file-syncer.yaml
sync/file-syncer-config.yaml

This should enable file syncer for test-infra and set up an idea of how the config will look.
Note that the exclude functionality of file syncer is currently broken https://github.com/BetaHuhn/repo-file-sync-action/issues/276.

Enable syncer for test-infra

---

.github/workflows/security.yaml

- :bug: Use regular build command instead of codeql/autobuild
/kind bug
This should fix the build of kn-plugin-event, caused by https://github.com/github/codeql/issues/12010
Fixes https://github.com/knative-sandbox/kn-plugin-event/issues/258

:bug: Use regular build command instead of codeql/autobuild

---

.github/workflows/lint.yaml
composite/style/github_actions/action.yml

actionlint runs shellcheck on github actions and does not seem to understand the GHA preferred `"name=value" >> "$GITHUB_ENV"` paradigm without throwing an error.
- :bug: Fix bug

Disable shellcheck on GHAs

---

composite/style/yaml/action.yml

- :broom: Update or clean up current behavior

Disable line-length rule for yamlint

---

.github/workflows/reusable-security.yaml

- :broom: Run CodeQL on its own job to avoid interference
/kind cleanup
The CodeQL should be run as a separate job, as it adds its libraries to `LD_PRELOAD`, which can have an impact on other tools, or at the very least, cloud the output.
- https://github.com/knative/test-infra/actions/runs/4616884538/jobs/8164115127?pr=3784#step:10:40

:broom: Run CodeQL on its own job to avoid interference

---

composite/style/shell/action.yml

reviewdog would have to have the changed files variable passed to each tool otherwise with the files changed which might be vendor files which is a problem. The beginning logic of the suggester handles the changed files fine and has a wider scope.
- :bug: Fix bug

Parse added files only for reviewdog

---

.github/workflows/reusable-security.yaml

- Adds Go vulnerability reporting using the [tool](https://go.dev/security/vuln/) from the Go sec team.

Go vulnerability reporting

---

.github/workflows/reusable-style.yaml
composite/style/shell/action.yml

/cc @kvmware 
This change suppresses this error which is in every repo:
```
REDACTED  C02CW0CDP3YY  ~  Desktop  Git  kn-test-infra   eventing-slack-channels  1✎  1⚑  ERROR  $  shellcheck prow/jobs/run_job.sh --external-sources 
In prow/jobs/run_job.sh line 19:
source "$(dirname "${BASH_SOURCE[0]}")"/../../vendor/knative.dev/hack/library.sh
^-- SC1091 (info): Not following: ./../../vendor/knative.dev/hack/library.sh: openBinaryFile: does not exist (No such file or directory)
For more information:
https://www.shellcheck.net/wiki/SC1091 -- Not following: ./../../vendor/kna...
REDACTED  C02CW0CDP3YY  ~  Desktop  Git  kn-test-infra   eventing-slack-channels  1✎  1⚑  ERROR  $  shellcheck prow/jobs/run_job.sh --external-sources -e SC1091
```
Also, we grant the worklows …

Exclude SC1091 checks

---

composite/style/shell/action.yml

- Don't run the shell style actions in the vendor directory
- Pass the `reporter` config to `action-shfmt` as a `reviewdog_flags` config to prevent the following warning:
```
Warning: Unexpected input(s) 'reporter', valid inputs are ['github_token', 'workdir', 'level', 'filter_mode', 'fail_on_error', 'reviewdog_flags', 'shfmt_flags']
```
Fixes #145

Shell style action enhancements

---

.github/workflows/reusable-style.yaml

Some repositories have `third_party` folders (e.g. [eventing-istio](https://github.com/knative-sandbox/eventing-istio/tree/main/third_party)), which code styles are kind out of our control. Therefor we should exclude these subfolders form the style checks.

Exclude `third_party` folders from style checks

---

composite/style/shell/action.yml

- Related [commit](https://github.com/knative/actions/commit/dba968a2068ecaa4be1fd0bb9aedde16c9a37971)
- The shfmt action does not accept the `reporter` config (either as part of `with` or passed in as a `reviewdog_flags`) so this PR removes it from the action-shfmt configuration.

Remove reporter config from action-shfmt

---

.github/workflows/reusable-helper-go-style.yaml

Removing gofmt as goimports does the work of gofmt
Fixes #115

removing-redundant-go-fmt

---

.github/workflows/reusable-releasability.yaml

Reusability actions was failing in this repo: https://github.com/vmware-tanzu/sources-for-knative
Realized it was because an extra quotes on the script, here is the fix :)

Reusability fix

---

sync/workflows/synced-go-test.yaml

- Allow secrets inheritance in unit test workflow
@upodroid @cardil PTAL
A follow-up to my previous PR #211 per docs:
https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow

Allow secrets inheritance in unit test workflow

---

.github/workflows/reusable-go-test.yaml

FYI @Cali0707 
Once again, I haven't read the docs completely and assumed `secrets:` inputs don't required definition on yamls. 
/cc @cardil @upodroid

Add codecov token to reusable action inputs

---

.github/workflows/reusable-go-build.yaml
.github/workflows/reusable-go-test.yaml

- :gift_heart: Run Go tests for each module
/kind enhancement
Fixes #

:gift_heart: Run Go tests for each module

---

composite/style/yaml/action.yml

- Fix pip install in python based action step
Related to: 
https://github.com/knative/infra/issues/530
/cc @upodroid @skonto @cardil

Fix pip install in python based action step

---

composite/style/yaml/action.yml

- Pin python version to 3.11
@upodroid PTAL, we have noticed that GH runners may vary on Ubuntu version. Spanning between 24 and 22 LTS release, the culprit is that Ubuntu 22 has default Python 3.10 that doesn't have `--break-system-package` yet. For our limited use case it seems like a good enough to pin the version. WDYT?
https://github.com/actions/runner-images/blob/ubuntu22/20241006.1/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime
FYI, per our chat earlier.
/cc @ReToCode @skonto

Pin python version to 3.11

---

.github/dependabot.yaml

- Specify directories containing action.yml files
Directories are not traversed further, per the error and actual dependabot feature issue.
```
updater | 2024/10/16 07:42:53 ERROR <job_901912085> Error during file fetching; aborting: /composite/<anything>.yml not found
```
/cc @upodroid

Specify directories containing action.yml files

---

setup-go/action.yaml

- Bump golang to 1.23
@upodroid @dprotaso @knative/knative-release-leads I wonder if we should jump on Go 1.23 before the next release cycle. What's your preference? 
I'll follow-up with knative/infra PR for prow images if we agree to proceed.

Bump golang to 1.23

---

.github/workflows/reusable-helper-go-style.yaml

- :broom: Bump golangci-lint version so it works with newer Go version. The older version was getting OOM with newer Go.
*NOTE*: this might introduce new warning in knative projects, we will have to update them accordingly.

Bump golangci-lint version

---

.github/workflows/reusable-helper-go-style.yaml

In #249 the golangci-lint-action was updated to v7. Anyhow v7 only supports golangci-lint = v (see [here](https://github.com/marketplace/actions/golangci-lint#compatibility)):
> v7.0.0 supports golangci-lint v2 only.
Also removing the `go` flag, as this seems not to be supported in golangci-lint v2 anymore

Update go-style action to use golangci-lint v2.0

---

.github/workflows/reusable-helper-go-style.yaml

This PR (https://github.com/knative/actions/pull/254) broke the action because we needed to bump the golangci version

bump golangci version that works with the action
