.github/workflows/knative-go-build.yaml
.github/workflows/knative-go-test.yaml
.github/workflows/knative-releasability.yaml
.github/workflows/knative-release-notes.yaml
.github/workflows/knative-security.yaml
.github/workflows/knative-stale.yaml
.github/workflows/knative-style.yaml
.github/workflows/knative-verify.yaml

- Move reusable workflows to actions repo
/kind <kind>
Fixes #knative/test-infra/issues/2994
```release-note
```
**Docs**
```docs
```

add reusable workflows

---

.github/workflows/go-build.yaml
.github/workflows/go-test.yaml
.github/workflows/lint.yaml
.github/workflows/releasability.yaml
.github/workflows/release-notes.yaml
.github/workflows/security.yaml
.github/workflows/stale.yaml
.github/workflows/style.yaml
.github/workflows/verify-codegen.yaml

This fixes the panic in golangci-lint: https://github.com/golangci/golangci-lint-action/issues/440

update action versions

---

.github/workflows/security.yaml

- :gift: Configurability of Unicode Control Characters check
/kind enhancement
Follows up on https://github.com/knative-sandbox/.github/pull/166

:gift: Configurability of Unicode Control Characters check

---

go/downstream-test/README.md
go/downstream-test/action.yaml

- add go/downstream-test
replaces: https://github.com/knative-sandbox/actions-downstream-test
usage: https://github.com/knative/pkg/pull/2507

add go/downstream-test

---

go/downstream-test/README.md
go/downstream-test/action.yaml

Fixes: https://github.com/knative/actions/issues/28

Infer the module name from the go.mod file

---

.github/workflows/lint.yaml

Fixes https://github.com/knative/test-infra/issues/2392
Idea is to suggest changes before reporting anything failing.
Note: this does have a side effect where if a change is suggested and not accepted then potentially can merge things that are not linted. However, suggesting linting and not having it accepted is better than no linting. Maybe in the future we should just auto-commit the changes instead of asking the PR owner to accept the changes and leave the suggestions for things like misspell etc.

make linting great again

---

.github/workflows/lint.yaml
.github/workflows/reusable_style.yaml

🐛 replace references of personal forked repo  with knative repo

---

.github/workflows/go-build.yaml
.github/workflows/reusable-go-build.yaml
go/downstream-test/action.yaml

- :gift: Use Knative ls-tags tool
/kind enhancement
Related https://github.com/knative/test-infra/pull/2995
Unblocks https://github.com/knative-sandbox/kn-plugin-event/pull/229
```release-note
Use Knative ls-tags tool instead of janky scripts that fail
```

:gift: Use Knative ls-tags tool

---

.github/workflows/file-syncer.yaml

Should fix https://github.com/kvmware/actions/actions/runs/3242366032

fix double quote error

---

.github/workflows/go-build.yaml
.github/workflows/reusable-go-build.yaml
go/downstream-test/action.yaml

Follow up to #72
Follow up to https://github.com/knative/test-infra/pull/3574

:broom: Simplify the ls-tags execution

---

.github/workflows/style.yaml

- :bug: Do not check vendor dir from sum-modules for Lints
/kind bug
Fixes https://github.com/knative-sandbox/kn-plugin-event/pull/229
```release-note
Do not check vendor dir from sum-modules for Lints
```

:bug: Do not check vendor dir from sum-modules for Lints

---

.github/workflows/style.yaml

- :bug: Don't look at vendor or third_party regardless of location
/kind bug
Fixes https://github.com/knative-sandbox/kn-plugin-event/actions/runs/3277218392/jobs/5394215090
```release-note
Don't look at vendor or third_party regardless of location
```

:bug: Don't look at vendor or third_party regardless of location

---

.github/workflows/style.yaml

It seems that the go version needs to change to everything involved in the action

Fixed Style action

---

.github/workflows/lint.yaml

1. Renames the reusable_style lint workflow to reusable-style
- :bug: Renames the reusable_style lint workflow to reusable-style
/kind bug
Fixes #100

Fixes Lint workflow not working

---

.github/workflows/reusable-go-test.yaml

- 🐛 fix: Fix go-test exec params
Fixes #105 
/cc @knative/productivity-writers

fix: Fix go-test exec params

---

composite/style/yaml/action.yml

remove defunt `tecoli-com/actions-use-python-tools`
only report errors for yamllint because reviewdog will fail the check on warnings

Install yamlfixer-opt-nc directly

---

.github/workflows/lint.yaml

- :broom: Update or clean up current behavior

Enable yamllint for this repo

---

.github/workflows/reusable-helper-go-style.yaml
.github/workflows/reusable-style.yaml

Pass only changed golang files to golang linter
- :bug: Fix bug

Lint only changed golang files

---

.github/workflows/reusable-helper-go-style.yaml
.github/workflows/reusable-style.yaml

This reverts commit 058b8af14f2e10c6c82d33adbb4192be6e1763f5.
Having this does not take into consideration the whole project

Revert "Lint only changed golang files (#119)"

---

composite/style/yaml/action.yml

- :broom: Update or clean up current behavior

Use yamllint rules for fixer as well

---

.github/workflows/reusable-style.yaml
composite/style/yaml/action.yml

Don't lint vendor correct env for yaml linter

---

.github/workflows/reusable-go-build.yaml
.github/workflows/reusable-releasability.yaml
.github/workflows/reusable-security.yaml
go/downstream-test/action.yaml

- :broom: Use extracted tools from knative.dev/toolbox
/kind cleanup
Related https://github.com/knative/toolbox/pull/3
Related https://github.com/knative/community/issues/1291

:broom: Use extracted tools from knative.dev/toolbox

---

composite/style/shell/action.yml

/cc @kvmware 
Fixing a typo from #140

Action doesn't use short major version

---

composite/style/shell/action.yml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Cleanup shell lint action

---

composite/style/shell/action.yml

-
-
-
/kind <kind>
Fixes #
```release-note
```
**Docs**
```docs
```

Use reviewdog shfmt for easier install

---

composite/style/shell/action.yml

Shellfmt does not have a straight forward way to filter out directories https://github.com/mvdan/sh/issues/288.

Remove shellfmt

---

.github/workflows/reusable-security.yaml

- Continues https://github.com/knative/actions/pull/167
- Follows guidelines here https://github.com/github/codeql/issues/13992
- Need by this PR https://github.com/knative/serving/pull/14568, see this [run](https://github.com/knative/serving/actions/runs/6653489641/job/18079562592?pr=14568).

Support 1.21 for codeQL

---

.github/workflows/reusable-go-build.yaml
.github/workflows/reusable-go-test.yaml
.github/workflows/reusable-helper-go-style.yaml
.github/workflows/reusable-security.yaml
.github/workflows/reusable-verify-codegen.yaml

/assign @upodroid 
/assign @dsimansk

use knative/actions/setup-go

---

.github/dependabot.yaml

use dependabot to update actions

---

.github/workflows/reusable-go-test.yaml

- 🐛 Add token field to codecov config
Part of the story discussed on Slack and to be discussed on Productivity WG meeting. 
This a placeholder fix if we decide to proceed with org wide `CODECOV_TOKEN` to fix coverage uploads from `main` branches.
/cc @cardil @upodroid 
/hold

Add token field to codecov config

---

.github/workflows/reusable-helper-go-style.yaml

bump golangci-lint

---

.github/workflows/reusable-go-test.yaml

- :lady_beetle: Prevent slash from appearing in coverage random ID
/kind bug
See: https://stackoverflow.com/a/6102233/844449
Fixes https://cloud-native.slack.com/archives/C04LY4M2G49/p1725366161644159
Follows up on https://github.com/knative/actions/pull/223

:lady_beetle: Prevent slash from appearing in coverage random ID

---

.github/dependabot.yaml

- Update actions in all directories
Relying only on `directory: "/"` doesn't bump other actions. 
E.g.: https://github.com/knative/actions/blob/main/composite/style/yaml/action.yml#L15
/cc @upodroid @dprotaso @skonto @ReToCode

Update actions in all directories

---

setup-go/action.yaml

Policy: https://github.com/knative/community/blob/main/mechanics/GOLANG-POLICY.md

bump go version to 1.24
